### ISSUE TITLE
你好，请问以下下面的错误怎么解决？

### ISSUE THREAD

**Issue by AYAY998** [Lee-zix/RE-GCN#17]
Traceback (most recent call last):
  File "E:\知识图谱\RE-GCN-master\src\main.py", line 442, in <module>
    run_experiment(args)
  File "E:\知识图谱\RE-GCN-master\src\main.py", line 234, in run_experiment
    loss_e, loss_r, loss_static = model.get_loss(history_glist, output[0], static_graph, use_cuda)
  File "E:\知识图谱\RE-GCN-master\src\rrgcn.py", line 212, in get_loss
    evolve_embs, static_emb, r_emb, _, _ = self.forward(glist, static_graph, use_cuda)
  File "E:\知识图谱\RE-GCN-master\src\rrgcn.py", line 160, in forward
    temp_e = self.h[g.r_to_e]
IndexError: tensors used as indices must be long, byte or bool tensors，代码没动过，除了改了一下UTF-8的编码格式，剩下的都是Github上一样的，为什么会报这种错误？

**Comment by AaronKevinAA** [comment]
我也是这个问题，你解决了嘛？
